version: '3.8'

services:
  casos:
    build: ./casos
    container_name: sisepi-casos
    volumes:
      - shared_data:/data
    networks:
      - sisepi-net
    restart: unless-stopped

  estadisticas:
    build: ./estadisticas
    container_name: sisepi-estadisticas
    volumes:
      - shared_data:/data
    depends_on:
      - casos
    networks:
      - sisepi-net
    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: sisepi-gateway
    environment:
      CASOS_URL: http://casos:5001
      ESTADISTICAS_URL: http://estadisticas:5002
    ports:
      - "8080:5000"
    depends_on:
      - casos
      - estadisticas
    networks:
      - sisepi-net
    restart: unless-stopped

networks:
  sisepi-net:
    driver: bridge

volumes:
  shared_data:
